on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install requirements
        run: uv pip install -r requirements.txt
        env:
          UV_SYSTEM_PYTHON: 1
      - name: Build
        run: python setup/build.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VocalScript-${{ matrix.os }}
          path: dist/*
          retention-days: 1
