on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            container: debian:oldstable
    container: ${{ matrix.container }}
    steps:
      - name: Install container packages
        if: matrix.container == 'debian:oldstable'
        run: |
          apt update
          apt install -y g++
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --locked
      - name: Build
        run: uv run scripts/build.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ runner.os }}
          path: dist/*
          retention-days: 1
